sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t arwalh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true arwalh/docker-react npm run test
# deploy:
#   provider: elasticbeanstalk
#   region: us-west-2
